---
# PLUGINS
# ==========================================

# Startup
# -------
- repo: Shougo/dein.vim

# - repo: flazz/vim-colorschemes

# - repo: arcticicestudio/nord-vim

# - repo: thinca/vim-localrc

- repo: christoomey/vim-tmux-navigator

# - repo: junegunn/vim-peekaboo

# - repo: tpope/vim-sleuth

# - repo: itchyny/vim-gitbranch

# - repo: itchyny/vim-parenmatch

- repo: vim-airline/vim-airline

- repo: vim-airline/vim-airline-themes

# - repo: ryanoasis/vim-devicons

- repo: itchyny/vim-cursorword
  hook_add: |
    autocmd MyAutoCmd FileType denite,qf,nerdtree let b:cursorword=0
    autocmd MyAutoCmd InsertEnter * let b:cursorword=0
    autocmd MyAutoCmd InsertLeave * let b:cursorword=1

- repo: mhinz/vim-startify
#   hook_add: |
#     # autocmd User Startified setlocal cursorline
#     # let g:startify_custom_header = [
#                 # \ '                               ',
#                 # \ '            __                 ',
#                 # \ '    __  __ /\_\    ___ ___     ',
#                 # \ '   /\ \/\ \\/\ \ /'' __` __`\  ',
#                 # \ '   \ \ \_/ |\ \ \/\ \/\ \/\ \  ',
#                 # \ '    \ \___/  \ \_\ \_\ \_\ \_\ ',
#                 # \ '     \/__/    \/_/\/_/\/_/\/_/ ',
#                 # \ ]
#     let g:startify_list_order = [
#                 \ ['   My most recently used files'],
#                 \ 'files',
#                 \ ['   My most recently used files in the current directory:'],
#                 \ 'dir',
#                 \ ['   These are my bookmarks:'],
#                 \ 'bookmarks',
#                 \ ['   These are my commands:'],
#                 \ 'commands',
#                 \ ]
#     let g:startify_enable_special         = 1
#     let g:startify_files_number           = 8
#     let g:startify_relative_path          = 1
#     let g:startify_change_to_dir          = 1
#     let g:startify_update_oldfiles        = 1
#     let g:startify_skiplist = [
#                 \ 'COMMIT_EDITMSG',
#                 \ 'bundle/.*/doc',
#                 \ '/data/repo/neovim/runtime/doc',
#                 \ '/Users/mhi/local/vim/share/vim/vim74/doc',
#                 \ ]
#     let g:startify_bookmarks = [
#                 \ { 'v': '~/.vimrc' },
#                 \ { 'z': '~/.zshrc' },
#                 \ { 'a': '~/.aliases' },
#                 \ { 't': '~/.tmux.conf' },
#                 \ { 'b': '~/Dotfiles/bootstrap.sh' },
#                 \ ]


# " call dein#add('junegunn/fzf', { 'build': './install' })
# " call dein#add('junegunn/fzf.vim', { 'depends': 'junegunn/fzf' })

# ==========================================
# Completion
# ----------

- repo: Shougo/deoplete.nvim
  depends: context_filetype.vim
  if: has('nvim') && empty($VIM_MINIMAL)
  on_event: InsertEnter
  hook_source: |
    source $VIMPATH/config/plugins/deoplete.vim
    call deoplete#enable()

- repo: Shougo/echodoc.vim
  if: empty($VIM_MINIMAL)
  on_event: CompleteDone
  hook_post_source: call echodoc#enable()

# - repo: Raimondi/delimitMate
#   on_i: 1
#   hook_source: |
#     let g:delimitMate_expand_cr = 1
#     let g:delimitMate_excluded_ft = 'html'

# - { repo: Shougo/context_filetype.vim, lazy: 1, if: empty($VIM_MINIMAL) }
# - { repo: Shougo/neco-vim, on_ft: vim, if: empty($VIM_MINIMAL) }
# - { repo: Shougo/neco-syntax, on_source: [ neocomplete.vim, deoplete.nvim ]}

- repo: davidhalter/jedi-vim
  if: empty($VIM_MINIMAL)
  on_ft: python
  hook_add: |
    let g:jedi#completions_enabled = 0
    let g:jedi#auto_vim_configuration = 0
    let g:jedi#smart_auto_mappings = 0
    let g:jedi#show_call_signatures = 1
  hook_source: |
    let g:jedi#use_tag_stack = 0
    let g:jedi#popup_select_first = 0
    let g:jedi#popup_on_dot = 0
    let g:jedi#max_doc_height = 100
    let g:jedi#quickfix_window_height = 10
    let g:jedi#use_splits_not_buffers = 'right'

# Only NeoVim ------------------------------

- repo: zchee/deoplete-jedi
  if: has('nvim') && empty($VIM_MINIMAL)
  on_ft: python
  on_i: 1
  hook_source: autocmd MyAutoCmd FileType python setlocal omnifunc=

- repo: tweekmonster/deoplete-clang2
  if: has('nvim') && empty($VIM_MINIMAL)
  on_ft: [ c, cpp ]

- repo: wellle/tmux-complete.vim
  if: has('nvim') && empty($VIM_MINIMAL)
  on_i: 1
  hook_add: let g:tmuxcomplete#trigger = ''

- repo: https://github.com/bradford-smith94/quick-scope

- repo: https://github.com/kshenoy/vim-signature
- repo: https://github.com/SirVer/ultisnips
  hook_source: |
    let g:UltiSnipsSnippetsDir = "~/Dotfiles/vim/.vim/my_snippets/"
    let g:UltiSnipsEditSplit = "context"
    augroup load_ultisnips
        autocmd!
        autocmd FileType python,c,c++,latex call - repo :#load('ultisnips')
                    \| execute 'autocmd! load_ultisnips' | doautocmd FileType
    augroup END
    let g:SuperTabDefaultCompletionType = "context"
    let g:UltiSnipsExpandTrigger = "<tab>"
    set runtimepath+=~/.vim/my_snippets/
    let g:UltiSnipsSnippetDirectories=["UltiSnips", "my_snippets"]

- repo: https://github.com/honza/vim-snippets

- repo: https://github.com/xtal8/traces.vim                 # highlight for commands
  hook_source: |
    let g:traces_whole_file_range = 0

- repo : 'https://github.com/tpope/vim-commentary'             # commentary
- repo : 'https://github.com/tpope/vim-surround'               # delete, change and add such surroundings in pairs
- repo : 'https://github.com/tpope/vim-repeat'                 # plugins support
- repo : 'https://github.com/tpope/vim-endwise'                # compition for contructions
- repo : 'https://github.com/tpope/vim-unimpaired'
- repo : 'https://github.com/tpope/vim-abolish'
- repo : 'https://github.com/tpope/vim-fugitive'                       # git wrapper
# seesions
- repo : 'https://github.com/tpope/vim-obsession'
- repo : 'https://github.com/dhruvasagar/vim-prosession'
  hook_source: |
    let g:prosession_tmux_title = 0
    let g:prosession_on_startup = 0

## themes
- repo : 'https://github.com/vim-airline/vim-airline'
- repo : 'https://github.com/vim-airline/vim-airline-themes'
- repo : 'https://github.com/blueyed/vim-diminactive'
- repo : 'https://github.com/myusuf3/numbers.vim'              # relitive numbers
- repo : 'https://github.com/chriskempson/base16-vim'

- repo : 'https://github.com/junegunn/goyo.vim'                # clean centered view
- repo : 'https://github.com/junegunn/limelight.vim'           # highlight current paragraf

- repo: 'https://github.com/machakann/vim-highlightedyank'

- repo: 'https://github.com/w0rp/ale'                         # linter
- repo: 'https://github.com/ervandew/supertab'

- repo: 'https://github.com/octol/vim-cpp-enhanced-highlight'
- repo: 'https://github.com/godlygeek/tabular'
- repo: 'https://github.com/vim-scripts/a.vim'                # switch .cpp .h
- repo: 'https://github.com/nelstrom/vim-visual-star-search'  # search selection
- repo: 'https://github.com/mhinz/vim-startify'               # startup screen
- repo: 'https://github.com/vim-scripts/Tagbar'               # togle tagbar

- repo: 'https://github.com/jpalardy/vim-slime'               # slime : send text to interpreter
- repo: 'https://github.com/ddrscott/vim-side-search'         # search over files
- repo: 'https://github.com/xtal8/traces.vim'                 # highlight for commands

- repo: 'https://github.com/Ron89/thesaurus_query.vim'        # synonims
- repo: 'https://github.com/rhysd/vim-grammarous'

